#!/bin/bash

LISBOA_ORIENTE=94-31039
POMBAL_STATION=94-34645
PORTO_CAMPANHA=94-2006
SANTA_APOLONIA_STATION=94-30007
DEPARTURE=17:30
ARRIVAL=19:07
. /home/murilo-oliveira/CP/TICKET_BUYER/.venv/bin/activate
python3 /home/murilo-oliveira/CP/TICKET_BUYER/ticket.py $SANTA_APOLONIA_STATION $POMBAL_STATION $DEPARTURE $ARRIVAL
open /home/murilo-oliveira/CP/TICKET_BUYER/finish.png