#!/bin/bash

LISBOA_ORIENTE=94-31039
POMBAL_STATION=94-34645
PORTO_CAMPANHA=94-2006
SANTA_APOLONIA_STATION=94-30007
DEPARTURE=18:30
WAIT_FOR_OPEN_TIME="--wait"
. /home/murilo-oliveira/CP/TICKET_BUYER/.venv/bin/activate
python3 /home/murilo-oliveira/CP/TICKET_BUYER/ticket.py $SANTA_APOLONIA_STATION $POMBAL_STATION $DEPARTURE $WAIT_FOR_OPEN_TIME
open /home/murilo-oliveira/CP/TICKET_BUYER/finish.png